server:
  port: 8070
  servlet:
    path: /
mybatis:
  type-aliases-package: com.eleven.five.entity
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///cp_test
    username: root
    password: root
  jpa:
    show-sql: false
  devtools:
    restart:
      additional-paths: /caipiao
      enabled: false
#logging.level.com.eleven.five.mapper: debug

